# Site settings

description: > # this means to ignore newlines until "baseurl:"

baseurl: "/myblog/" # the subpath of your site, e.g. /blog/
url: "http://franchescomora.github.io/myblog/" # the base hostname & protocol for your site


# Build settings
markdown: kramdown
